-- MySQL Script generated by MySQL Workbench
-- 08/23/16 20:14:19
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema bd_Atletas
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema bd_Atletas
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `bd_Atletas` DEFAULT CHARACTER SET utf8 ;
USE `bd_Atletas` ;

-- -----------------------------------------------------
-- Table `bd_Atletas`.`Atleta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_Atletas`.`Atleta` (
  `idAtleta` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `apellido` VARCHAR(45) NOT NULL,
  `fNacimiento` DATE NOT NULL,
  `documento` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idAtleta`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_Atletas`.`Maraton`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_Atletas`.`Maraton` (
  `idmaraton` INT NOT NULL AUTO_INCREMENT,
  `fecha` DATE NOT NULL,
  `organizador` VARCHAR(45) NOT NULL,
  `estado` ENUM('PROCESO', 'TERMINADO') NOT NULL,
  PRIMARY KEY (`idmaraton`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_Atletas`.`Carrera`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_Atletas`.`Carrera` (
  `idCarrera` INT NOT NULL AUTO_INCREMENT,
  `fecha` DATE NOT NULL,
  `estado` ENUM('PROCESO', 'TERMINADO') NOT NULL,
  `Atleta_idAtleta` INT NOT NULL,
  `Maraton_idmaraton` INT NOT NULL,
  PRIMARY KEY (`idCarrera`),
  INDEX `fk_Carrera_Atleta_idx` (`Atleta_idAtleta` ASC),
  INDEX `fk_Carrera_Maraton1_idx` (`Maraton_idmaraton` ASC),
  CONSTRAINT `fk_Carrera_Atleta`
    FOREIGN KEY (`Atleta_idAtleta`)
    REFERENCES `bd_Atletas`.`Atleta` (`idAtleta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Carrera_Maraton1`
    FOREIGN KEY (`Maraton_idmaraton`)
    REFERENCES `bd_Atletas`.`Maraton` (`idmaraton`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
